services:
  # Name of your Spring Boot service
  hello-world-aws:
    build: . 
    ports:
      - "8080:8080" 
    environment:
      # Spring Boot application properties
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/database
      SPRING_DATASOURCE_USERNAME: postgres  
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_PROFILES_ACTIVE: postgresql
    depends_on:
      - postgres  # This service depends on the postgres container

  postgres:
    image: postgres:latest 
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: database